### ISSUE TITLE
How to use ThreadHelper.JoinableTaskFactory in net5+?

### ISSUE THREAD

**Issue by lennartb-** [microsoft/vs-threading#1016]
I have a net6-windows project with WPF, where a VSTHRD001 warning is reported with the following code:

```
protected override async void OnStartup(StartupEventArgs e)
{
    ///...
    await Current.Dispatcher.InvokeAsync(() => 
    {
       // The actual culture comes from e.args, for the sake of an example use a hardcoded value.
       CultureInfo.CurrentCulture = new CultureInfo("enGB");
    });
    ///....
}
``` 

According to the docs for VSTHRD001 this should rather be done with a JTF, which requires the `ThreadHelper` class from the `Microsoft.VisualStudio.Shell.Framework` package. However, since that package has been (apparently) build with net472, VS will then complain with a "Package was restored using .NetFramework 4.7.2..." warning. Is there a more current package available, or a different way to do this in NET5/6?

**Comment by AArnott** [comment]
As the VSTHRD001 documentation says, in non-VS applications there should be another way to get to a `JoinableTaskFactory` or `JoinableTaskContext` as defined by that application. You should _not_ try to use the `ThreadHelper` from VS in your own application.

**Comment by lennartb-** [comment]
Ok, I didn't properly gather that from the docs. To be clear: do the analyzers generally make sense on a non VS-related application (e.g., a standalone WPF exe project)?

**Comment by AArnott** [comment]
> do the analyzers generally make sense on a non VS-related application (e.g., a standalone WPF exe project)?

Yes. They are designed to be general for any project (whether WPF, WinForms, console app, or even ASP.NET or ASP.NET Core).

> but others seem fairly specific to VS-related code.

Which ones?

> Avoiding an async void method when overriding OnStartup (which comes from WPF)

`async void` is hazardous in general as it will crash your app when it throws an unhandled exception. And using `async void` for `OnStartup` isn't ever required anyway because it's not like WPF will wait for your async work as part of startup -- WPF has no idea that you still have scheduled work after OnStartup returns. So if you ever want to spin off async work from a sync method whose signature you cannot change, JTF.RunAsync is a reasonable go-to solution. 

> Creating a JTF

I'm not sure what you mean by that. JoinableTaskFactory creation is fine and analyzers won't complain.

> Using JTF.Run in an internal method when your entry point is internal

If you really want to synchronously block OnStartup to do what could otherwise be async code, you can go ahead and do so by suppressing the warning at that location. There are places we do this in VS as well. It's not a VS vs. non-VS thing. It's just an anti-pattern, but has exceptional cases where you need to do it, and that's why C# allows suppressing specific warnings using `#pragma warning disable VSTHRDxxx`.

> Especially since all examples I found while searching online usually violate 1) and/or don't use a JTF at all.

Well, that's simply because most WPF apps don't use JTF. :) WPF apps probably number in the hundreds of thousands while WPF apps that use JTF may number in the dozens or maybe hundreds.

**Comment by lennartb-** [comment]
> Which ones?

It was purely subjective on my part, based on the examples given in the analyzers usually relating to VS, e.g. the usage of `ThreadHelper` in VSTHRD001 or `IVsSolution` in VSTHRD010. (The namespace as well, but I read elsewhere that it's just that the library is maintained by the VS team).

> I'm not sure what you mean by that. JoinableTaskFactory creation is fine and analyzers won't complain.

I had some difficulties figuring out how to create one the right way. Creating a single `JoinableTaskContext` for the application and getting the JTF via the `Factory` property seems the way to go according to [your comment here](https://stackoverflow.com/questions/55535494/do-i-use-a-joinabletaskfactory-with-aspnetcore#comment125674425_60746471).

> If you really want to synchronously block OnStartup to do what could otherwise be async code, you can go ahead and do so by suppressing the warning at that location. There are places we do this in VS as well. It's not a VS vs. non-VS thing. It's just an anti-pattern, but has exceptional cases where you need to do it, and that's why C# allows suppressing specific warnings using #pragma warning disable VSTHRDxxx.

It's not that I _want_ it :) It's just a matter of figuring out when its okay to suppress something.
