### ISSUE TITLE
VSTHRD100 (avoid async void) doesn't work for local functions

### ISSUE THREAD

**Issue by drewnoakes** [microsoft/vs-threading#1074]
#### Bug description

VSTHRD100 fires for `async void` methods, but not for local functions.

#### Repro steps

```c#
class C
{
    async void M() // VSTHRD100 
    {
        async void L() {} // no diagnostic
    }
}
```

#### Expected behavior

VSTHRD100 should fire on local function `L` in the above example.

#### Actual behavior

VSTHRD100 does not fire on local function `L` in the above example.

- Version used: 17.3.22-alpha
- Application (if applicable): dotnet/project-system

**Comment by drewnoakes** [comment]
This library is using a relatively old version of `Microsoft.CodeAnalysis.Common` (2.10.0) which doesn't appear to support local functions.

Bumping to the latest version (4.2.0) requires increasing the target framework from `netstandard1.3` to `netstandard2.0`.

Any concerns with that?

**Comment by drewnoakes** [comment]
This diagnostic should also fire for `async void` lambdas.

**Comment by drewnoakes** [comment]
I ended up not needing to bump those levels in the PR, but forgot to update this issue.

**Comment by AArnott** [comment]
#1075 regressed VSTHRD100 because now it fires on lambdas, which is the purview of VSTHRD101. As a result, we had an insertion blockage due to [new warnings](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/413182?_a=files&base=1&iteration=2) that were all redundant with VSTHRD101 anyway.

This *issue* was about identifying local functions, but the PR to address that added lambda detection as well, which I should have noticed since that was in the PR title and in fact was the _only_ thing the new tests covered rather than covering the local function scenario.

**Comment by AArnott** [comment]
@drewnoakes would you like to take another try at this issue, including rolling back the lambda detection?

**Comment by drewnoakes** [comment]
Seems like https://github.com/microsoft/vs-threading/pull/1076 should cover it.

**Comment by AArnott** [comment]
Thank you!
