### ISSUE TITLE
Provide sample .editorconfig files for different project types

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [microsoft/vs-threading#1095]
**Background**

Some of the VS Threading analyzers are only applicable for certain project types. For example, [VSTHRD011](https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD011.md) and [VSTHRD012](https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD012.md) are probably not generally applicable to ASP.NET Core apps, because these apps do not have a main UI thread.

**Proposal**
@AArnott suggested at https://github.com/microsoft/vs-threading/issues/470#issuecomment-1284921600 that it might be nice to provide sample `.editorconfig` files for different project types, such as WPF or ASP.NET Core

**Possible downsides**
Does it even make sense for ASP.NET Core apps to use the `vs-threading` library? For example, if an ASP.NET Core app uses `LazyAsync<>`, is that a code smell?

**Comment by csi-lund** [comment]
This would be good, I was forward here due to and issue enforcing VSTHRD200 via the editor config without this library - it was found that is did not apply to interfaces which was a standard we wanted. However here was are faced with the applicability of VSTHRD200 to controllers in an asp.net application.

Perhaps using this analayzer is not correct in our context but are you aware of an alternative?

**Comment by Bosch-Eli-Black** [comment]
@csi-lund https://github.com/microsoft/vs-threading/issues/470 has some guidance on which warnings are applicable to ASP.NET Core apps 🙂

**Comment by csi-lund** [comment]
Thanks for the tip !

**Comment by Bosch-Eli-Black** [comment]
Np! 🙂
