### ISSUE TITLE
VSTHRD103 does not trigger on ?.Result

### ISSUE THREAD

**Issue by bjornhellander** [microsoft/vs-threading#1235]
#### Bug description
VSTHRD103 does not trigger when accessed using null-conditional operator.

#### Repro steps
```
public class TestClass
{
    public async Task DoAsync()
    {
        var a = SomethingAsync().Result; // Triggers VSTHRD103
        var b = SomethingAsync()?.Result; // Does NOT trigger VSTHRD103
    }

    private Task<int> SomethingAsync() => Task.FromResult(1);
}
```

#### Expected behavior
Both uses of the Result property should trigger VSTHRD103.

#### Actual behavior
Only the first use of the Result property triggers VSTHRD103.

- Version used: Microsoft.VisualStudio.Threading.Analyzers 17.7.30

#### Additional context
N/A

**Comment by sujitmahapatra** [comment]
The issue you're encountering where VSTHRD103 doesn't trigger when accessed using the null-conditional operator (?.) might be a limitation of the current version of the Microsoft.VisualStudio.Threading.Analyzers library. To work around this issue, you can follow these steps:

1. **Manually Check for Null**:

   Instead of relying solely on the null-conditional operator, manually check if the result of `SomethingAsync()` is null before accessing the `Result` property. This way, you can ensure that VSTHRD103 is triggered:

   ```csharp
   public async Task DoAsync()
   {
       var a = SomethingAsync().Result; // Triggers VSTHRD103
       var result = SomethingAsync();
       if (result != null)
       {
           var b = result.Result; // Triggers VSTHRD103
       }
   }
   ```

   By manually checking for null, you make sure that the analyzer recognizes the potential issue with accessing `Result` in a non-async context.

2. **Check for Updates**:

   Keep an eye on updates to the `Microsoft.VisualStudio.Threading.Analyzers` library. The behavior you described might be a bug that is fixed in a later version of the library. Check for updates and upgrade to a newer version if it becomes available.

3. **Report the Issue**:

   If you believe this is a genuine bug in the analyzer and it's not fixed in the latest version, consider reporting the issue to the Visual Studio team on their GitHub repository. Provide a clear description of the problem and any relevant code examples to help them understand and address the issue.

   Here is the link to the GitHub repository where you can report issues: https://github.com/microsoft/vs-threading

   Reporting the issue directly to the maintainers can help ensure that it gets the necessary attention and is addressed in a future release of the library.

**Comment by AArnott** [comment]
Thanks for the report @bjornhellander.

@sujitmahapatra I can't fault what you say. I'm guessing though that it's AI-generated text (and as I guess, that's an interest of yours from your github profile). The text seems both customized yet boilerplate like AI would have generated. Advising that the issue be reported as a github issue when that is exactly what you're responding to feels... a bit AI like.
Am I right?

**Comment by sujitmahapatra** [comment]
Hello,

I appreciate your engagement in this discussion. I want to clarify that I
am indeed a human user, and my responses are not generated by AI. I
apologize if my previous message seemed unusual or automated.

You can verify my authenticity by checking my GitHub profile, where you
will find information about my software development interests and
activities.

The suggestion to report the issue as a GitHub issue might seem redundant,
but it was intended to emphasize the importance of official issue tracking
for problem resolution within the open-source community.

I'm here to assist and engage in genuine conversations related to software
development and any other topics of interest. If you have any further
questions or concerns, please feel free to ask.

Thank you for your understanding.

Best regards,

Sujit
