### ISSUE TITLE
RequestIds in PostExecutionStart/Stop events are not unique for different call stacks

### ISSUE THREAD

**Issue by jialongcheng** [microsoft/vs-threading#1302]
#### Bug description
PostExecutionStartEvent and PostExecutionStopEvent both contain a request ID. Users should be able to uniquely identify the events based on the request Id and correlate the start/stop event pairs for processing.

In our performance testing, we found out that sometimes different tasks had same request ID. Here is a snapshot of the events:
![image](https://github.com/microsoft/vs-threading/assets/40867840/59e8a50a-5276-48c9-ab9e-706daaa36289)

These events have the same id but from the call stacks of the Start events, they are clearly not from the same task.

**Comment by AArnott** [comment]
The requestId comes from calling `object.GetHashCode()` on a unique object. I believe the default implementation of this method returns something based on its memory address, so that's pretty wild that you found cases where the same address happens to be used for the same type of object but unique instances across time. 

I expect we could use an interlocked incrementing integer to ensure uniqueness.

**Comment by davkean** [comment]
Note, it's an int not a long so it needs to truncate the address, so it could be two addresses.

**Comment by weltkante** [comment]
Looking at the fixing PR it was taking a hash on a SendOrPostCallback on a SC, probably was a bad idea, since SC is public and delegates are cached/reused where possible rather than being unique?

**Comment by weltkante** [comment]
Looking at the current PR, when NonConcurrentSynchronizationContext is installed as current SC its post method uses the hash of its SendOrPostCallback - a caller controlled delegate in public API is not guaranteed to be unique, in fact Roslyn will try to cache and reuse it wherever possible.
