### ISSUE TITLE
Generic overloads of ReentrantSemaphore.ExecuteAsync that work with Task<T>

### ISSUE THREAD

**Issue by drewnoakes** [microsoft/vs-threading#1309]
I'm converting code from `AsyncSemaphore` to `ReentrantSemaphore`. Whereas before I could use `using`:

```c#
using AsyncSemaphore.Releaser semaphoreReleaser = await _semaphore.EnterAsync();

// do stuff
return true;
```

Now we have to pass a delegate. I tried writing a local function e.g.:

```c#
bool b = await _semaphore.ExecuteAsync(DoThingInternalAsync);

async Task<bool> DoThingInternalAsync()
{
    // ...
    return true;
}
```

But there's no overload for that.

**Comment by drewnoakes** [comment]
I can make my own extension method for this I suppose.

**Comment by drewnoakes** [comment]
I can make do with the current API. Migration just had a few bumps. API changes would make that smoother, though I suppose `ValueTask` support is nice if you don't expect to wait often.

**Comment by AArnott** [comment]
You have to pass a delegate because only a delegate allows the class to track ExecutionContext sufficient to be "JTF-aware". This is why JTF.Run and RunAsync themselves take delegates.

As for adding an overload that takes `Func<Task<T>>` so your local function works, why not just define your local function to return `ValueTask<T>` instead? That's just a one-word change and your originally proposed code in the issue description would work.
