### ISSUE TITLE
VSTHRD002 doesn't trigger when configure await is used

### ISSUE THREAD

**Issue by baywet** [microsoft/vs-threading#1354]
#### Bug description

Whenever ConfigureAwait is in use, some rules do not trigger.

#### Repro steps

```csharp
using var client = new HttpClient();
var response = client.GetStringAsync("https://httpbin.org/headers").ConfigureAwait(false).GetAwaiter().GetResult();
```

Does not trigger.

#### Expected behavior

Rule to trigger when ConfigureAwait is in use

#### Actual behavior
What happened instead of what you expected.

- Version used: 17.11.20
- Application (if applicable):

**Comment by AArnott** [comment]
Thanks for your report. Using `.ConfigureAwait(bool)` in combination with `GetAwaiter().GetResult()` is a bug, because in fact configuring the await and the sync-blocking behaves identically to not calling `ConfigureAwait` at all. But still, I've seen it before, as have you. I'll update the analyzer.
