### ISSUE TITLE
VSTRHD012 get reported in a lazy when it shouldn't

### ISSUE THREAD

**Issue by baywet** [microsoft/vs-threading#1356]
#### Bug description
I get a VSTRHD012 report when newed up in a lazy when I shouldn't not get one.

#### Repro steps

```csharp
        private static readonly Lazy<JoinableTaskContext> LazyJoinableTaskContextInstance =
            new Lazy<JoinableTaskContext>(() => new JoinableTaskContext(), LazyThreadSafetyMode.PublicationOnly);

```

#### Expected behavior

No error reported.

#### Actual behavior

VSTRHD012 reported to the user.

- Version used: 17.11.20
- Application (if applicable):

**Comment by AArnott** [comment]
I'm trying to understand why VSTHRD012 would fire on this at all, since none of these APIs take a JoinableTaskFactory.

Aside, it seems like a very bad idea to create a JoinableTaskContext lazily this way, since it could mean creating it on some other thread than the main thread. And anyway, creating it is quite cheap, and should only be done once. Why not create it directly instead of lazily?

**Comment by baywet** [comment]
I don't have the historical context that lead to this implementation. In general I agree that it should not be done in a Lazy. This is probably because the implementer saw that context implemented IDisposable and got spooked by potentially performance impacts.

As for the parameter, can you clear some confusion for me please? I thought the context was passed to the factory, and not the other way around. So I'm not sure what this constructor would be expecting here?

**Comment by AArnott** [comment]
> I thought the context was passed to the factory, and not the other way around. So I'm not sure what this constructor would be expecting here?

The JoinableTaskFactory already has the JoinableTaskContext. And as the JTC is the root, you don't create it using a JTF instance.

The issue here (as I just investigated it) is that on .NET 5+, the `System.Lazy<T>(T)` constructor exists, and that makes it look like an alternative ctor overload exists that takes a `JoinableTaskContext` instead of the `Func<JoinableTaskContext>` overload. 
So ya, this is a false positive. But given we don't advise this lazy pattern anyway, and special casing it would be relatively expensive, I'm going to Won't Fix this.

You can always add a local suppression for this warning around this particular field if you'd prefer that to removing the use of Lazy.

**Comment by baywet** [comment]
Makes sense, thanks for looking into this. 

Just as a follow up: I'm getting a sense that even a static read-only field would not be a good fix for this pattern? Since there is no guarantee it'd be on the right thread.
Can you confirm it needs to be an instance field?

**Comment by AArnott** [comment]
A guarantee should exist that the `JoinableTaskContext` is created:
1. By the time it is first needed.
2. On the right thread and with the right `SynchronizationContext`, or with the right values for these passed to its constructor.

These two requirements can be hard to code correctly if done any later than early on startup when there's only one thread, after its SyncContext has been set up. If you wait till you have multiple threads, then it can happen that the first user might be on a non-main thread, and might inadvertently cause the lazy initializer to execute the factory on its thread instead.
You can mitigate this by storing the Thread and SynchronizationContext objects such that you can reference them later from your lazy value factory, but that's just more complexity with typically 0 value.

I generally hate mutable statics. While a `static readonly` for this `JoinableTaskContext` object isn't mutable, it does leave initialization to the CLR on whatever thread happens to first touch the class (or member) in question. In fact I think the CLR doesn't even document when or where field initializers are executed except to say it's done "before their value is retrieved for the first time". So I avoid field initializers whenever the thread they may happen to run on is important. 

I try to use instance fields/properties for most everything. But it can be very convenient to have a static member with a JTC/JTF on it, so... this is one way how I might do it:

```cs
class Program {
  private static JoinableTaskContext? context;

  public static JoinableTaskContext JoinableTaskContext => context ?? throw new InvalidOperationException();

  static int Main() {
    SynchronizationContext.Current = new WinFormsSyncContext(); // or whatever
    context = new();
    // rest of your code
}
```

Alternatively (and my favorite) keep the JTC field an instance one, and pass around your Program class (or whatever you call it) so that unit tests can have perfect isolation from each other instead of fighting over static values.
