### ISSUE TITLE
Rename the project to not include Visual Studio

### ISSUE THREAD

**Issue by JoeStead** [Microsoft/vs-threading#193]
I've been looking for a package like this for quite some time, however as I do not use Visual Studio, I glanced over this originally because I thought it was something Visual Studio specific. 

Removing the VS part of the project will increase discoverability in the future.

**Comment by AArnott** [comment]
We might do this, except as it has shipped several times already, renaming it would be a breaking change that we can't tolerate.

Do you think any kind of labeling in its description or on nuget.org would help prevent people from passing over it?

**Comment by JoeStead** [comment]
I understand that it's breaking, but that isn't necessarily a bad thing. The package itself doesn't have a huge amount of downloads currently, and the versioning seems to be tied to the VS versions, which again doesn't make sense. 

The analyser itself is a different discussion, and potentially should be separated out?

**Comment by AArnott** [comment]
Are you talking about renaming the package, or the assembly, or both?

Renaming the assembly would be unacceptable, as it's part of the public API for VS and other applications.
Renaming the package would be rather disruptive as well since folks already using the package wouldn't know where to find the new one to continue getting updates--or even that they need to change the ID in their dependency.

**Comment by Neme12** [comment]
:(
