### ISSUE TITLE
VSTHRD100: Should not report event handlers

### ISSUE THREAD

**Issue by fahadabdulaziz** [Microsoft/vs-threading#447]
#### Bug description
VSTHRD100 reports about async void methods, it should not report on event handlers.

#### Repro steps
```csharp
Console.CancelKeyPress += Console_CancelKeyPress;

private async void Console_CancelKeyPress(object sender, ConsoleCancelEventArgs e)
        {
            await HelloWorld();
        }
```

#### Expected behavior
Should not report on event handlers

- Version used: 15.8.209

**Comment by Therzok** [comment]
Afaik, ISymbol comparisons should be done via Equals, not `==`.

https://github.com/Microsoft/vs-threading/blob/master/src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs#L97

**Comment by fahadabdulaziz** [comment]
Sure I can test any fix or build, just tell me when the build is published to NuGet..

**Comment by fahadabdulaziz** [comment]
@AArnott, Just tested the update, the problem still present..

**Comment by AArnott** [comment]
Thanks, @fahadabdulaziz. Can you share your repro steps and/or solution?

**Comment by fahadabdulaziz** [comment]
It occurs on this code:
```csharp
private async void ShowReviewedSessions(object __sender, EventArgs __e)
{
}
```
I have no experience on developing analyzers but I think it check the parameters usually if a method has two parameters (object, EventArgs) or whatever derives from EventArgs, the method should be ignored.

**Comment by AArnott** [comment]
This issue tracks exactly the opposite desired behavior as #469.

**Comment by AArnott** [comment]
@fahadabdulaziz Can you elaborate on why you feel async void is _not_ evil when used for event handlers?

**Comment by fahadabdulaziz** [comment]
Because async Task is not accepted as event handlers :-)

Method:
```csharp
private async Task ShowReviewedSessions(object __sender, EventArgs __e)
{
}
```
will not be accepted as event handler

**Comment by AArnott** [comment]
True, but the recommended pattern is:

```cs
obj.Event += (s, e) => joinableTaskFactory.RunAsync(() => OnEventAsync(s, e));
}

private async Task OnEventAsync(object sender, EventArgs e)
{
   // async code here.
}
```

This is preferable both because exceptions won't crash the app and (more particularly) [the app won't close in the middle of an async event handler](https://github.com/Microsoft/vs-threading/blob/master/doc/cookbook_vs.md#how-to-write-a-fire-and-forget-method-responsibly) (that might be saving a file, for example).

**Comment by fahadabdulaziz** [comment]
This pattern will not work with WinForms designer

**Comment by sharwell** [comment]
@fahadabdulaziz How did you get the WinForms designer to generate an async event handler? I did not realize that was a feature and can't figure out how to trigger it.

**Comment by fahadabdulaziz** [comment]
I meant this part, it could not be generated by WinFroms:
```csharp
obj.Event += (s, e) => joinableTaskFactory.RunAsync(() => OnEventAsync(s, e));
}
```

**Comment by sharwell** [comment]
@fahadabdulaziz Thanks, I updated my previous comment to show what the recommended pattern looks like with WinForms.

**Comment by fahadabdulaziz** [comment]
That would work perfect

**Comment by Dunge** [comment]
@sharwell Could you expend on the usage of your recommended pattern? I don't quite get it. What is obj? What exactly is joinableTaskFactory? Is it an instance of `Microsoft.VisualStudio.Threading.JoinableTaskFactory` shared by all your events? Seems a bit weird to include something in the VisualStudio namespace. Will the call to it be awaited before continuing in our event handler? Will the UI thread be freed while doing the async task?

**Comment by AArnott** [comment]
@dunge: 

> What is obj? 

It's a placeholder name for whatever object you are adding an event handler to.

> What exactly is joinableTaskFactory? Is it an instance of Microsoft.VisualStudio.Threading.JoinableTaskFactory shared by all your events?

The app should have an app-wide `JoinableTastContext` instance, from which your event handlers can access an instance of `JoinableTaskFactory`. Learning what these types are is outside the scope of this issue, but we have docs in this repo's `doc` folder that go over that.

> Seems a bit weird to include something in the VisualStudio namespace. 

The VisualStudio namespace is merely an artifact of the team funding this library and not an indication that this is VS-specific.

> Will the call to it be awaited before continuing in our event handler? 

No. The entire body of a `void`-returning event handler that needs to be implemented asynchronously will be in the delegate passed to JTF.RunAsync. You cannot then await the call to JTF.RunAsync in this context because the event handler method itself should not use the `async` modifier.

> Will the UI thread be freed while doing the async task?

Yes, except when your handler is actively executing code that requires the main thread. In this respect the behavior is very similar to what you're used to without using JTF.

> Every articles about calling async code in UI event handler always propose "async void", but none talks about the VSTHRD100 warning.

JTF primarily becomes interesting when you need to block the main thread at some point in your app without deadlocking while waiting for what would otherwise be async work. So it may not apply to _every_ application.

**Comment by silkfire** [comment]
@asaf92 Could you also add the WinForms/VS extension syntax to the **VSTHRD100.md** page?

```csharp
var menuItem = new MenuCommand(HandleEvent, commandId);

private void HandleEvent(object sender, EventArgs e)
{
   _ = joinableTaskFactory.RunAsync(async () =>
   {
      // async code
   });
}

```

**Comment by AArnott** [comment]
@silkfire, thanks for the suggestion. I've made the change.

**Comment by RevZero** [comment]
@AArnott Can you point to a good article about JoinableTaskFactory / JoinableTastContext? [This](https://github.com/Microsoft/vs-threading/blob/main/doc/cookbook_vs.md#how-to-write-a-fire-and-forget-method-responsibly) gives some interesting advice, but it already assumes deeper knowledge about the topic.

Is this even considered "normal practice" to handle async calls in void event handler? Why not just make event handler async (which is acceptable according to microsoft documentation) and just make sure to handle exceptions?

```
        private async void SomeHandler()
        {
            try
            {
                // Await if desired
                await SomethingAsync();
                SomeOtherWork();

                // OR plan a continuation and handle task status there
                SomethingAsync().ContinueWith(t =>
                {
                    if (t.IsCompletedSuccessfully)
                    {
                        SomeOtherWork();
                    }
                }).Forget();
            }
            catch (Exception ex)
            {
                // log exception
            }
        }

```
With respect to JoinableTask. You wrote "The app should have an app-wide JoinableTastContext instance, from which your event handlers can access an instance of JoinableTaskFactory".

So would I prefer this 

 ```
           JoinableTaskContext ctx = new();
            ctx.Factory.RunAsync(async () => await Task.Delay(1));
```

over this

```
            JoinableTaskFactory jtf = new(new JoinableTaskContext());
            jtf.RunAsync(async () => await Task.Delay(1));

```

Would it even matter? How to properly initialize the Context or the factory? 

> new JoinableTaskContext()
> "Initializes a new instance of the JoinableTaskContext class assuming the current thread is the main thread and Current will provide the means to switch to the main thread from another thread."

So that is probably what is desired?

**Comment by AArnott** [comment]
> Why not just make event handler async

A few reasons: 
1. Uncaught exceptions will crash the process. As you point out, you can mitigate this with a try/catch block.
2. Exiting the app will pay no regard to completing the async work first, which may lead to data corruption if it was doing any kind of I/O. This can only be mitigated by using the patterns you found in that document. But if you handler doesn't do I/O, you're probably OK.
3. Tearing down the AppDomain may crash the process if any managed threads are executing within than AppDomain, and async void methods are entirely untrackable. Normal .NET process shutdown doesn't include this step, but if you have a native apphost for your managed code, AppDomain teardown may apply.

> The app should have an app-wide JoinableTastContext instance, from which your event handlers can access an instance of JoinableTaskFactory.... So would I prefer this...

We're getting out of scope of the issue. If you have follow-up questions, please use Discussions.

Yes, the first option is closer. But your JoinableTaskContext should be stored in a shared field somewhere in your app and you should ensure you only create _one_ of them. Then you can use the Factory it creates, or create other factories based on that JoinableTaskContext, to use around your app.

> How to properly initialize the Context or the factory?

We're getting out of scope of the issue. If you have follow-up questions, please use Discussions.

The simplest way is to use the default constructor of JoinableTaskContext while on the main thread during app startup.
