### ISSUE TITLE
Applicability of vs-threading lib and analyzers in ASP.NET

### ISSUE THREAD

**Issue by abergs** [microsoft/vs-threading#470]
I'm simply wondering if there are any issues with using this nuget and analyzer in an asp.net project?

1: Will it introduce anything bad?
2: Are there any analyzers (AsyncLazy?) that does not apply to a asp.net project and should be ignored?

I asked this question on SO for increased visibility/SEO when others encounter this: https://stackoverflow.com/questions/55103194/using-vs-threading-in-asp-net-project

**Comment by AArnott** [comment]
[VSTHRD200](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD200.md) may not be a good fit if your controller methods are async but you don't want Async as a suffix to those methods because that would influence the public URLs.
[VSTHRD012](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD012.md) may not apply either, since you probably don't have a JoinableTaskFactory in an ASP.NET environment.

A couple of others may not apply ([VSTHRD001](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD001.md) and [VSTHRD003](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD003.md)), but they won't likely produce diagnostics in that context either so not so much of an issue.

**Comment by Bosch-Eli-Black** [comment]
@AArnott Would [VSTHRD011](https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD011.md) also not be applicable to ASP.NET Core apps?

**Comment by AArnott** [comment]
VSTHRD011 is probably not necessary in that case, since it's primarily around avoiding deadlocks in an environment with a main thread.

**Comment by Bosch-Eli-Black** [comment]
@aarnott Thanks! 🙂

Do you think it'd be worth noting in the documentation which analyzers aren't applicable to apps that don't have a main thread? (Or maybe more broadly, apps that don't have a threading context, although I'm not sure if that's correct?)

**Comment by AArnott** [comment]
I think that's a good idea. In fact, we could perhaps document it in terms of .editorconfig files that have the rule severity configured for each app type, so folks could just copy and paste the rule severities into their own files. Care to open a new issue to track that (docs and/or .editorconfig files)?

**Comment by Bosch-Eli-Black** [comment]
Filed at https://github.com/microsoft/vs-threading/issues/1095 🙂
