### ISSUE TITLE
Create extension or tool for Microsoft.VisualStudio.Threading.Analyzers

### ISSUE THREAD

**Issue by unsafePtr** [microsoft/vs-threading#471]
I found Microsoft.VisualStudio.Threading.Analyzers package really helpful in the usual development. However, installing it in every project as a NuGet package is very uncomfortable. Can we consider to create the VisualStudio extension or dotnet tool for this package?

**Comment by AArnott** [comment]
The VS extension was attempted in #452 and was abandoned for lack of demand and inability to deliver on all requirements.
We won't be writing a dotnet tool either.

Can you add a PackageReference to the analyzer nuget package in a Directory.Build.props file instead of your project files? Then you're doing the work only once per repo instead of once per project.

**Comment by unsafePtr** [comment]
@AArnott, thank you for your suggestion. Do you have any idea how to make it work at the Visual Studio level? Like, any project which is opened to apply these analyzers.
Think issue can be closed.

**Comment by AArnott** [comment]
The only way to get analyzers to run on every project regardless of have a `PackageReference` in the project or an imported file would be to have a VSIX installed in VS to add the analyzers.
