### ISSUE TITLE
!dumpasync simply gives an error right away

### ISSUE THREAD

**Issue by jasonmalinowski** [microsoft/vs-threading#496]
I loaded AsyncDebugTools.dll into a WinDBG session trying to diagnose an async hang, and when running `!dumpasync` I just get:

    Failed to parse the output of !name2ee: 

and absolutely nothing else happens. No further error message is shown either -- I suspect something was supposed to appear after the colon in the message but it's not.

- Version used: 15.8.168+g9c5efca7b3.RR
- Application (if applicable): WinDBG 10.0.18924.1002

**Comment by AArnott** [comment]
That's because the current source code in this repo is based on parsing command output and if it's not normal for some reason it throws us off. This can happen when it's not a heap dump, or you're missing SOS or symbols can't load, or a variety of other things.
We have a newer version of !dumpasync that I'd love for you to try. We're planning to replace the current implementation in this repo with the new one soon.

**Comment by slav** [comment]
@AArnott - how do we get the new version to try?

**Comment by AArnott** [comment]
It's not available publicly yet. Hopefully soon.

**Comment by drewnoakes** [comment]
This appears to be released now. @AArnott is the latest version the one you're referring to above?

**Comment by AArnott** [comment]
Yes
