### ISSUE TITLE
Building projects targeting .net 4.8 fails

### ISSUE THREAD

**Issue by HeikoAdams** [microsoft/vs-threading#501]
#### Bug description
When using the current version 16.3.13 localy building projects targeting .net framework 4.8 raises a lot of warnings:
"IDE1003	Die Analysetoolassembly "C:\Users\h.adams\.nuget\packages\microsoft.visualstudio.threading.analyzers\16.3.13\analyzers\cs\Microsoft.VisualStudio.Threading.Analyzers.CodeFixes.dll" hängt von "netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" ab, diese Assembly wurde aber nicht gefunden. Analysetools werden möglicherweise nicht ordnungsgemäß ausgeführt, wenn die fehlende Assembly nicht als Analysetoolreferenz hinzugefügt wird."

These warnings are causing builderrors with Azure DevOps server (on premise) using vs-buildtools 2019.

#### Repro steps
Update/install the Microsoft.VisualStudio.Threading.Analyzers for a project targeting .NET Framework 4.8. Cleanup the project. Restart Visual Studio. Rebuild the proect.

#### Expected behavior
Building projects should not cause any warnings or error related to the updated nuget.

#### Actual behavior
Local building raises warnings because netstandard v2 assembly could not be found, automated builds with Azure DevOps Server are failing.

- Version used: 16.3.13
- Application (if applicable): Visual Studio 2017 (15.9.14) / Azure DevOps Server 2019.1 RC2 with VS Buildtools 2019 (16.2.0)

**Comment by HeikoAdams** [comment]
Any progress on this issue?

**Comment by AArnott** [comment]
It doesn't repro for me. Here's what I tried. What are you using? Can you share a repro?

[ClassLibrary1.zip](https://github.com/microsoft/vs-threading/files/3681560/ClassLibrary1.zip)

**Comment by HeikoAdams** [comment]
Even with the latest release the build fail.s for me.
I'll attach the azure devops server 2019.1 build logs. Maybe they help.
[logs_3807.zip](https://github.com/microsoft/vs-threading/files/3689820/logs_3807.zip)

**Comment by AArnott** [comment]
Thanks for the logs.
The failure in the logs is not the same one you shared originally. Instead of complaining about netstandard.dll it's complaining about System.Runtime.CompilerServices.Unsafe.dll.

I see the failure is not in compilation but in the sgen.exe tool. I don't have any experience recently with this tool, but I strongly suspect the problem is close to what you originally shared, where sgen.exe wants to find all assemblies that are transitively referenced by your application and it can't find a dependency of System.Runtime.CompilerServices.Unsafe.dll. I'm not sure what dependency it can't find (`C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\Facades\netstandard.dll` is explicitly provided on the command line). But none of this is the fault of the analyzers. Analyzers do not add any assembly references to your project. I don't even see the analyzer or codefixes assembly on the list of assemblies going into sgen.exe, making me even more confident that it's unrelated to the analyzers.

Have you looked at project.assets.json to see what is bringing in the `system.runtime.compilerservices.unsafe` package reference?

**Comment by HeikoAdams** [comment]
After updating Microsoft.VisualStudio.Threading to the latest version **every** project of my solution got that lines injected:
`      "System.Runtime.CompilerServices.Unsafe/4.5.2": {
        "type": "package",
        "compile": {
          "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll": {}
        },
        "runtime": {
          "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll": {}
        }
      },`

Maybe because of the netstandard 2.0 dependency at first position?

**Comment by AArnott** [comment]
Your original report was talking about the Microsoft.VisualStudio.Threading.*Analyzers* package, which doesn't have the dependency on `System.Runtime.CompilerServices.Unsafe`. But certainly if you're talking about the Microsoft.VisualStudio.Threading package, yes that brings in a few dependencies. If you're targeting net48 then netstandard2.0 wouldn't have as much to do with it (directly anyway) since the Microsoft.VisualStudio.Threading package has a target for net472 so netstandard2.0 wouldn't be relevant, but even the net472 targeting dependencies in the package bring in other dependencies from corefx including those likely targeting netstandard2.0.

So if your repro does indeed add ref assemblies (which the Microsoft.VisualStudio.Threading package would do) then you should add those assemblies to the search path or parameter list to sgen.exe so that it can find them.

**Comment by HeikoAdams** [comment]
But why claims the compiler (local and buildsystem) a missing **netstandard 2.0** assembly but my projects are targeting **net48**? This happens with every version > 16.0.102

**Comment by AArnott** [comment]
Because sgen.exe wants to see every single assembly (transitive closure of dependencies). Some assemblies that you reference transitively include those that reference netstandard.dll. sgen.exe wants to know where it is.
It doesn't matter that you target net48 -- net48 supports netstandard2.0 and some assemblies you're using targeted that.
