### ISSUE TITLE
UAP projects that reference vs-threading fail to compile with .NET Native

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-threading#557]
Due to https://github.com/dotnet/corert/issues/7372, the code below in vs-threading leads to .NET Native's compilation to fail:

https://github.com/microsoft/vs-threading/blob/8085d152503000c384b2da9025195da327206344/src/Microsoft.VisualStudio.Threading/InternalUtilities.cs#L160

**Comment by AArnott** [comment]
I'm drafting a change that adds a UAP10.0 target to the library that omits the problematic code. It also adds a UAP test project to the solution to verify that vs-threading never blocks UAP consumption again.

**Comment by AArnott** [comment]
@onovotny is there any way to add a `uap10.0` TFM to my library for the sake of the nuget package target being offered and a C# preprocessor define `WINDOWS_UWP`, but without breaking `dotnet build` or requiring the UWP SDK to be installed? I don't really need *anything* from UWP's SDK -- I just need another TFM with the uap name in my package so I can provide a special build of the library for it.

**Comment by onovotny** [comment]
You might be able to do it without the extras by defining the TFM locally like this:

https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/master/Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.csproj#L44-L61

Instead of `native`, you'd define `uap10.0` and then potentially one of the netstandard TFM's/NuGet moniker's here: https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/master/Microsoft.Toolkit.Uwp.Notifications/Microsoft.Toolkit.Uwp.Notifications.csproj#L46-L47

**Comment by AArnott** [comment]
Thanks for the tip. That sounds promising. So far though I can't find the right combination of properties to define to get restore and build working without warnings/errors. Any more tips?

[Here's what I've tried](https://github.com/AArnott/vs-threading/commit/5036d5d831ad756b4b0fab1a10b574a7a4c1fc86).

**Comment by sharwell** [comment]
What happens if you just use `Unsafe.AsPointer` instead?

**Comment by AArnott** [comment]
Not only does that side-step any need for *me* to target UAP, but it (surprisingly) _works_ on UAP (it doesn't even throw an exception). Thanks for the tip, @sharwell.

**Comment by sharwell** [comment]
Well alright then 😄
