### ISSUE TITLE
Is VSTHRD003 only applicable to use of JoinableTaskFactory

### ISSUE THREAD

**Issue by RehanSaeed** [microsoft/vs-threading#578]
I'm working on a UWP app which does not use `JoinableTaskFactory`. Does [VSTHRD003](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD003.md) still apply to my app.

I'm assuming that the analysers mentioned in https://github.com/microsoft/vs-threading/issues/470 are also applicable to me.

**Comment by AArnott** [comment]
Yes, The analyzers are good everywhere, although you *may* choose to turn one or two of them off, you shouldn't *need* to IIRC because the analyzers self-deactivate in contexts to which they don't apply.

Any GUI app (or other app that has a single threaded `SynchronizationContext`) would do well to use JTF, almost certainly. Strictly speaking though, you can deactivate VSTHRD003 and not use JTF if you *never* synchronously block anywhere (eg. using `Task.Wait()` or `Task.Result` or `Task.GetAwaiter().GetResult()`). But if you think you might (someday) need to synchronously block, you could use JTF and VSTHRD003 early on to make it easy to synchronously block when and if you need to.
