### ISSUE TITLE
Analyzer proposal: Do not return null from non-async Task method 

### ISSUE THREAD

**Issue by Evangelink** [microsoft/vs-threading#593]
Hi there,

I don't think such rule exists in the current codebase (or I failed to find it). Returning null from a non-async `Task` method will result in a null pointer at runtime but everything is fine at compile-time.

Non-compliant code:

```csharp
public Task<Person> GetPersonAsync(string name)
{
	// some code
    return null; 
}
```

Compliant code:

```csharp
public Task<Person> GetPersonAsync(string name)
{
	// some code
    return Task.FromResult<Person>(null);
}
```

The probability of such code is quite low but I saw something similar in a couple of places.

**Comment by AArnott** [comment]
I agree, this is a problem. I've seen it a few times including quite recently. 

However [C# 8 with its nullable ref types feature](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) has already solved the problem since it produces a warning if you return null from a method that returns a ref type unless it explicitly calls out that null is a possible result. I saw this week a PR of a repo that activated the nullable ref types feature that led to finding and fixing exactly this kind of error.

An analyzer here would certainly help more people in the short-term, but it's a low priority because it's already fixed for the long-term.

**Comment by Evangelink** [comment]
@AArnott Happy to provide a PR for this rule if that's ok for you.

**Comment by AArnott** [comment]
Sounds great! Thank you.

Most of our analyzers are based on C# syntax types, which limits the applicability to just C#. All new analyzers should ideally be written with Roslyn's Operation API if possible to make them applicable to VB as well. 
We'll also require tests for the analyzer.
I don't expect a code fix, but if you want to throw that in too (e.g. change `return null;` to `return Task.FromResult<T>(null);`), that's great.

**Comment by sharwell** [comment]
📝 Also, this analyzer probably shouldn't be active in `#nullable enable` code.

**Comment by Evangelink** [comment]
Is it ok to bump the version of `Microsoft.CodeAnlysis` used by this project? Otherwise I can't detect the `NullableContextOptions.Enable` context.

**Comment by sharwell** [comment]
@Evangelink you can use the light-up approach that I added in https://github.com/dotnet/roslyn-analyzers/pull/3338

**Comment by AArnott** [comment]
> Is it ok to bump the version of Microsoft.CodeAnlysis used by this project?

We'd have to review telemetry to see whether we can bump Microsoft.CodeAnalysis, since doing so would cut off support in our analyzers for all VS versions that didn't support C# 8, which is likely a bunch of users at this point.
So I like @sharwell's idea. 

But I also don't think it's a high priority to suppress the diagnostic in `#nullable enable` contexts. It would avoid a double-diagnostic, true, but it's a bad problem that folks should fix. It would also avoid a diagnostic if `Task?` is returned, but I would be really surprised if anyone did htat.

**Comment by Evangelink** [comment]
@sharwell I have imported the light-up you were mentioning but I have some trouble to use it in the code. I am guessing that I need to call https://github.com/dotnet/roslyn-analyzers/pull/3338/files#diff-f511c1ef47a631a8eac39ce6a6aa63a1R13 and then https://github.com/dotnet/roslyn-analyzers/pull/3338/files#diff-301549b614ad2d3cae248a250702293bR19 to detect if the method is inside a nullable enable context but I am not sure to understand what needs to be passed for the position argument.

**Comment by sharwell** [comment]
@Evangelink The position is the location in the source text to check. For this analyzer, either of the following locations (or both) could be checked. It seems unlikely for the locations to produce different values.

```
public $$Task MethodAsync()
{
  return $$null;
}
```

**Comment by Evangelink** [comment]
And now I am stuck on tests... I have updated to the latest version of the test sdk yet I am having a `error CS1024: Preprocessor directive expected` when using `#nullable enable` in the code. When trying to force the language version I can see that the highest version is 7.3, I guess I need 8. Is it ok to update roslyn on the test project? If so shall I go for the latest version or the minimal version with language 8?

**Comment by sharwell** [comment]
> Is it ok to update roslyn on the test project?

I would say yes.

> If so shall I go for the latest version or the minimal version with language 8?

3.3.1 or 3.5.0 would be the most likely candidates.

**Comment by Evangelink** [comment]
3.3.0 seems to be the minimal working version. v3.5 introduces a lot of warnings on your lightups. I would still need to add tests for the configuration at project level.

**Comment by sharwell** [comment]
> v3.5 introduces a lot of warnings on your lightups

This would only occur if the project where the light-up option are defined was upgraded. Only the test projects should be updated, and those don't directly call the light-up helpers.

> I would still need to add tests for the configuration at project level.

This is more difficult than you might expect, because even if you set it at the project level it will not be set in generated code. The test framework automatically tests both normal and generated code, so you have to:

1. Use the full form (likely necessary anyway so you can set the necessary parse option)
2. Disable the generated code check
