### ISSUE TITLE
Please separate the analyzer package from the library package

### ISSUE THREAD

**Issue by DaRosenberg** [microsoft/vs-threading#605]
Since some recent update, referencing `Microsoft.VisualStudio.Threading` also brings in all the analyzers. Not only to projects that directly reference `Microsoft.VisualStudio.Threading`, but to any projects in the solution that reference those projects, and so on.

To me this is a bit frustrating.

It's not that the analyzers are not good - they are excellent. I just think developers should be able to use the library, without necessarily using the analyzers. There may be good reasons:
- Some devs could be using other analyzers that perform the same tasks
- CPU utilization if there are a lot of analyzers running
- You may want to apply the analyzers selectively, not to your whole codebase (e.g. maybe you don't apply them to your test projects, etc.)

I think developers should have the choice, basically.

It would be better if these packages were separate. If the intent of this dependency is to have the analyzers also apply to the code base of the library itself, they can be referenced as private assets (so they don't transitively propagate).

**Comment by AArnott** [comment]
I sympathize. In fact another one of our own libraries is in the position that you're describing and we filed https://github.com/microsoft/vs-streamjsonrpc/issues/195 a while ago to track it. We want folks to be able to reference StreamJsonRpc without getting the threading analyzers, since the fact that the StreamJsonRpc library uses the vs-threading library is mostly an implementation detail.

That said, the priority for the threading library itself is that people use it properly, and most folks wouldn't think to install the analyzers package separately. So we're going to continue chaining in the analyzers package and keep chasing the nuget team to enable consuming packages to suppress the analyzer package, allowing both you and us to fix https://github.com/microsoft/vs-streamjsonrpc/issues/195 and similar issues.
