### ISSUE TITLE
VSTHRD103 should allow calling SemaphoreSlim.Wait(TimeSpan.Zero) in async method

### ISSUE THREAD

**Issue by irontoby** [microsoft/vs-threading#611]
#### Bug description
[Calling `SemaphoreSlim.Wait(TimeSpan.Zero)`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim.wait?view=netcore-3.1#System_Threading_SemaphoreSlim_Wait_System_TimeSpan_) "doesn't block. It tests the state of the wait handle and returns immediately."

#### Repro steps
```
public Task SomeMethodAsync()
{
    if (!_semaphoreSlim.Wait(TimeSpan.Zero))
        return;

    // code for entering semaphore
}
```

#### Expected behavior
Calling non-async `Wait()` should be allowed in the special cases where `Wait(0)` or `Wait(TimeSpan.Zero)` are called.

#### Actual behavior
`VSTHRD103` is raised (Call async methods when in an async method).

#### Additional context
Being able to attempt a lock but return immediately if other code is running can be useful in cases such as fetching a scarce resource on a background timer. There is no need to add an `await` in this case since it will never block.

**Comment by AArnott** [comment]
Your argument makes sense, but we don't have the time to special case arbitrary APIs based on very specific conditions under which the sync version is better than the async version.

I suggest you simply call `await semaphore.WaitAsync(0);` in your code, since from the docs it sounds like that won't yield so it won't add any noticeable perf hit for all but the most sensitive scenarios. 
And if you are in the most sensitive scenario, suppress the analyzer around that call with `#pragma warning disable VSTHRD103`.

**Comment by irontoby** [comment]
Understood, thanks for the feedback.
