### ISSUE TITLE
Documentation assumes JoinableTaskFactory is available

### ISSUE THREAD

**Issue by zmarty** [microsoft/vs-threading#612]
Hello Microsoft colleague(s),

We strictly use the analyzers package (Microsoft.VisualStudio.Threading.Analyzers) inside .NET Core 3.1 projects that have nothing to do with Visual Studio.

Documentation (for example for [VSTHRD002](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD002.md) and [VSTHRD110](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD110.md)) assumes JoinableTaskFactory is available. That is only the case if the code is a Visual Studio extension, which it is not.

So what can we do to fix the warnings without using JoinableTaskFactory? In one specific case, we need to start a fire-and-forget function inside a constructor, and constructors cannot be async.

**Comment by weltkante** [comment]
You generally cannot do fire-and-forget with async functions because any exception will be observed by the GC and terminate the process.

I usually have a helper method which observes exceptions from such calls, and handle them appropriately (e.g. logging)

> assumes JoinableTaskFactory is available. That is only the case if the code is a Visual Studio extension, which it is not.

You can create your own JoinableTaskContext and get the factory from there if you want to. Its certainly worth if you have a UI thread and use async, in order to avoid deadlocks.

**Comment by AArnott** [comment]
> Documentation (for example for VSTHRD002 and VSTHRD110) assumes JoinableTaskFactory is available. That is only the case if the code is a Visual Studio extension, which it is not.

You incorrectly assume that the MS.VS.Threading library is VS-specific. It is not. Dozens of apps I know of use this library, including JTF, to avoid or resolve their main thread deadlock issues. 
Even without a main thread and the deadlocks inherent with it, using JTF.Run to synchronously block instead of Task.Wait() is preferred because it helps you avoid [threadpool starvation](https://github.com/microsoft/vs-threading/blob/master/doc/threadpool_starvation.md). So as @weltkante suggests, you can create your own `JoinableTaskContext` in your application and use JTF just fine. So the analyzer and its documentation is still correct.

That said, if you don't want to do the above, the next thing I'd recommend is to disable VSTHRD002 since you've made a choice to disregard that recommendation, which particularly in a library *may* be the right choice. However if I were in a library and designing an API, I wouldn't offer any synchronous entrypoint to functionality that might need to call code that would most efficiently be done asynchronously. I would thereby push any requirement to be synchronous outside my library and into the app that's calling me. The app can decide whether to use Task.Wait() or use JTF to block.

> You generally cannot do fire-and-forget with async functions because any exception will be observed by the GC and terminate the process.

Not true, @weltkante. That was true in .NET 4.0, but .NET 4.5 stopped crashing when the finalizer encountered Tasks with unobserved exceptions.
That said, any spinoff of a Task without observing its exception is bad news. Just delete the code if you don't care to notice whether it fails or not. So "fire and forget" is generally a bad idea. "Fire and track" is a better approach if you don't want to await the code, where you still pass the Task to some system that tracks it for failures and reports exceptions somewhere that you'll notice them later.

> In one specific case, we need to start a fire-and-forget function inside a constructor, and constructors cannot be async.

You say you want fire-and-forget in a constructor. Then in that case you wouldn't want to *await* or to use `Task.Wait()` would you? You're just going to call an async method and drop its result on the floor. As I mention above, this is a Bad Idea. But if you really want to, you can suppress VSTHRD110 by simply doing _anything_ with the resulting Task. You could assign it to a local variable (and ignore it) or use our `Task.Forget()` extension method which is expressly for that purpose.

**Comment by zmarty** [comment]
We write backend code (Azure Functions to be more specific). We have multiple uses cases where the analyzers I mentioned show warnings/errors. One case is where in a static class constructor we have to call an asynchronous KeyVault library in order to get a secret (this particular case is NOT fire and forget).

Any ideas if MS.VS.Threading can be used directly in Azure Functions? I have no idea how heavy this is. Maybe JoinableTaskContext should be part of a separate smaller library, not sure.

**Comment by zmarty** [comment]
Also, if MS.VS.Threading can be used on other applications, you may want to clarify the description in the documentation: "The Microsoft.VisualStudio.Threading namespace contains APIs for use in Visual Studio SDK projects. You should use these APIs for asynchronous programming in Visual Studio. Doing so helps you avoid deadlocks"

https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.threading?view=visualstudiosdk-2019

**Comment by weltkante** [comment]
> Not true, @weltkante. That was true in .NET 4.0, but .NET 4.5 stopped crashing when the finalizer encountered Tasks with unobserved exceptions.

hmm, I was pretty sure I still observed this behavior way past 4.5 on Desktop and UWP but I just tested and you are right, all Core/Desktop/UWP don't terminate the process anymore. I'll try to remember not to use that argument anymore, sorry.

**Comment by AArnott** [comment]
@weltkante The docs weren't helpful on the topic either, as they described .NET 4.0 behavior only. I've sent a PR to fix this: https://github.com/dotnet/dotnet-api-docs/pull/4153

@zmarty I haven't written any Azure Functions myself, but I would be loathe to send a network request from a static class constructor. Besides forcing me to do it synchronously, static class constructors that experience exceptions are entirely *unrecoverable*. The process is screwed at that point. 

> Any ideas if MS.VS.Threading can be used directly in Azure Functions? I have no idea how heavy this is. Maybe JoinableTaskContext should be part of a separate smaller library, not sure.

Of course it can be used in Azure Functions. At the end of the day it's just a .NET library, so I can't imagine why it wouldn't work in Azure Functions. Now, the applicability of certain classes of course varies by application. I don't know why I'd move JoinableTaskContext into its own library. Most libraries offer *some* functionality that an app may not find useful. This library has many classes, and I assume most apps will only use a proper subset of them.

**Comment by AArnott** [comment]
> Also, if MS.VS.Threading can be used in other applications, you may want to clarify the description in the documentation:

Quite right, @zmarty. Thank you for bringing this to my attention. I've sent a message to the docs team to ask for a correction.
