### ISSUE TITLE
VSTHRD104: Expose an async method - even if this method is a constructor.

### ISSUE THREAD

**Issue by AgentFire** [microsoft/vs-threading#635]
#### Bug description
Compiler warning:

> Expose an async version of this method that does not synchronously block. Then simplify this method to call that async method within a JoinableTaskFactory.Run delegate.

#### Repro steps
Create a class, inside declare a construtor, inside put this:

```cs
class A{

public A() {
using (JoinableTaskContext ctx = new JoinableTaskContext())
{
    JoinableTaskFactory tf = new JoinableTaskFactory(ctx);
    tf.Run(() => Task.CompletedTask); // Expose an async version of this method that....
}

}
}
```

#### Expected behavior
Expecting that not to happen.

#### Actual behavior
It happens.

##### Version used: 
- Microsoft.VisualStudio.Threading, Version=16.6.0.0

**Comment by AArnott** [comment]
This is by design. While constructors cannot be async, they still aren't excused to synchronously block threads when the caller was async and could have avoided it.

The recommended pattern when you need an async constructor is to create a static async factory method that then calls a private constructor with the results of whatever the async operation was.

```cs
class A {
   public static A CreateAsync() {
        await Task.Yield();
        return new A();
   }

   private A() {
   }
}
```
