### ISSUE TITLE
Process.WaitForExitAsync

### ISSUE THREAD

**Issue by weltkante** [microsoft/vs-threading#665]
`Process.WaitForExitAsync` is added to .NET 5 with a different return type than the extension method provided in this library. Probably not a major issue, mainly will cause consumers of the library to trip up when switching to .NET 5 and the framework method is preferred over your extension method. Just thought I'd bring it up because the library doesn't compile against .NET 5 yet (tests fail to compile due to this but its easily fixed), feel free to close this issue if you don't have anything to follow up on.

see dotnet/runtime#28458 for the new API

**Comment by AArnott** [comment]
Thanks for the heads up. Yes, this does sound like it will be a hiccup for consumers of our API when they update to .NET 5 since the return type doesn't include the exit code any more. But I imagine it will be minimal distress for them.

Nothing to fix at this point, since we're not targeting .NET 5 yet.

**Comment by lostmsu** [comment]
Should be reopened.

**Comment by AArnott** [comment]
Thanks for bringing this up. Even though we target .NET 6 now, I don't know that there's anything we can do. Removing or changing our own API would be a binary breaking change for everyone. If we do nothing, it will be a _source-only_ breaking change for those who upgrade their target framework to include .NET 6 and call this API since the result value will be `Task` instead of `Task<int>` and they'll have to accommodate that. I can't see a 3rd, better alternative.

**Comment by lostmsu** [comment]
@AArnott how about adding `WaitForExitCodeAsync`?

**Comment by AArnott** [comment]
I don't see preserving the exit code return value in itself as valuable enough to add an API when it's already available via `Process.ExitCode` and by calling our existing API with the non-extension method syntax.
