### ISSUE TITLE
False positive for VSTHRD103 with Console.Error.WriteLine?

### ISSUE THREAD

**Issue by meziantou** [microsoft/vs-threading#672]
````
// VSTHRD103: use WriteLineAsync
Console.Error.WriteLine("repro"); 
Console.Out.WriteLine("repro"); 
````

`Console.Error` / `Console.Out` streams are synchronous, so I'm not sure there is any advantage to use WriteLineAsync instead of WriteLine. I think the rule should not report this case to avoid adding complexity to the code.

- Version used: 16.7.56
- Application (if applicable): VS 16.8.0 Preview 2.1

**Comment by AArnott** [comment]
This used to bother me too, but fixing it would require special casing recognition that you're calling through `Console`. `Console.Out` and `Console.Error` are just streams, and in general we should use async methods on streams when in async methods. 

But then I realized that in fact these streams sometimes _do_ block. if you have a console app in conhost.exe (the typical 20+ year old terminal window), selecting text in the window causes the output to freeze, and it very typically freezes the progress of whatever console app is printing to the output window. This is because STDERR/STDOUT aren't being read from by conhost when selection is active, and when the app is _synchronously_ writing to STDERR/STDOUT, that blocks the writer thread. Most console apps very quickly block whatever they're doing when they can't write to the console until their STDOUT write operation unblocks.
So in fact STDOUT/STDERR _do_ block sometimes, and using async APIs would prevent that from happening. Now, we might consider whether that's desirable, but it becomes a non-issue in the future because the new Windows Terminal application _doesn't_ block stdout/stderr for console apps when selection is in progress any more. But the point remains: there _does_ remain a virtue to async I/O even for stdout/stderr streams.
