### ISSUE TITLE
Consider adding an analyzer that flags mis-use of ConcurrentExclusiveSchedulerPair

### ISSUE THREAD

**Issue by Therzok** [microsoft/vs-threading#879]
#### Is your feature request related to a problem? Please describe.

I recently had a "brilliant idea" where instead of using a `SemaphoreSlim` or a `Task.WhenAny` loop to limit the amount of tasks queued to run work, I thought I could use `ConcurrentExclusiveSchedulerPair.ConcurrentScheduler` with a limit to how many tasks can run concurrently. I thought that, it would be a bit more optimized, in that it would not even run the code until the scheduler is ready to pop a task from its queue.

VS-Threading made it easy, by enabling the `await pair.ConcurrentScheduler` construct and then running it.

The problem? The scheduler is designed around synchronous tasks. So if you have any code that is going to run a continuation at any point, it could end up in a situation where it will break (i.e. the tasks are scheduled out of order or the tasks that are needed to run to continue execution of everything else end up in a scenario where they can't even be schedueld).

#### Describe the solution you'd like

An analyzer should flag the usage of `await ConcurrentExclusiveSchedulerPair.(Concurrent/Exclusive)Scheduler` when the continuation contains any non-synchronous code.

#### Describe alternatives you've considered

I'm not sure if there are any alternatives, it might still be up to the user to decide whether the behaviour is correct, but it could be error prone.

#### Additional context

If needed, ask away.

**Comment by AArnott** [comment]
I think the fundamental difference between using a semaphore to throttle and *any* `TaskScheduler` is that given as async operation that you want to throttle concurrency for, semaphores can reserve a slot for the entire async operation as a whole, whereas a `TaskScheduler` would throttle based on CPU time (or each sync segment of an async operation). Both are perfectly valid scenarios.

For example if your goal is to not flood a web API with more than 5 concurrent calls and you're using async HttpClient methods, then you should use a semaphore. But if you're goal is to limit local CPU utilization of a compute-heavy task, then you should use a throttling `TaskScheduler` so that any time spent asynchronously *awaiting* doesn't limit throughput on your CPU intensive activity.

You can read more about this on by blog post: [Limiting concurrency for faster and more responsive apps](https://devblogs.microsoft.com/premier-developer/limiting-concurrency-for-faster-and-more-responsive-apps/).

If I understand your analyzer proposal, the analyzer would discourage the TaskScheduler-as-throttle use case, which could redirect folks to a less optimal solution.

**Comment by Therzok** [comment]
I totally understand that, and I did read up on that blog post before opening this.

I think the main issue I was encountering was async boundaries in ConcurrentExclusiveSchedulerPair, and probably the scenario I encountered is really really specific that an analyzer for this wouldn't be of value in VS-Threading.

In any case, having it as a warning analyzer is definitely too much. Feel free to close the issue, this seems to be a more developer oriented decision than automated.

**Comment by Therzok** [comment]
The main thing I was leading to is that the ConcurrentExclusiveSchedulerPair usage with async code (not CPU heavy) could lead to problems, especially with continuation handling being deferred to the end of the scheduler - assuming it is a FIFO queue.
