### ISSUE TITLE
VSTHRD200 does not produce diagnostics when response is nullable ValueTask

### ISSUE THREAD

**Issue by rafal-mz** [microsoft/vs-threading#940]
#### Bug description

Analyzer is reporting diagnostic when return type is:
- `Task`
- `Task?`
- `Task<T>`
- `Task<T>?`
- `ValueTask`

Analyzer is not reporting diagnostic when used with:
- `ValueTask?`
- `ValueTask<T>?`

![image](https://user-images.githubusercontent.com/45458298/138313302-9a555e4c-7436-4585-856a-d8fec5ac2dc6.png)
![image](https://user-images.githubusercontent.com/45458298/138313395-16fd0644-d893-42bf-a1f3-d8dfe880e10a.png)

#### Repro steps
1a. Create static empty class `Class`
2a. Create empty static method returning `Task?`
3a. Change returning type to `ValueTask`?

1b. Create static empty class `Class`
2b. Create empty static method returning `Task<bool>`?
3b. Change returning type to `ValueTask<bool>`?

#### Expected behavior
Analyzer still report dignostic about method name

#### Actual behavior
Analyzer doesn't report diagnostic.

- Version used: 16.10.56
- Application: VS studio 2022 RC

**Comment by AArnott** [comment]
Nullable return types of async functions makes calling it safely very complicated. And in particular for value-types such as `ValueTask`, I can't imagine why `ValueTask?` would be a good return type. I think I'd sooner write an analyzer that warns against nullable return types for async methods (since `await SomeMethod()` would throw NullReferenceException).
